import { StyleSheet } from 'react-native';
import { theme } from '../../../../global/themas';

export const styles = StyleSheet.create({
  scrollContent: {
    padding: 24,
    paddingBottom: 40,
  },
  backButton: {
    marginBottom: 20,
    marginTop: 10,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  header: {
    marginBottom: 24,
  },
  kicker: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 12,
    color: '#999',
    letterSpacing: 2,
    marginBottom: 4,
  },
  titleBlack: {
    fontFamily: theme.fonts.headingBold,
    fontSize: 28,
    color: theme.colors.textPrimary,
    lineHeight: 32,
  },
  titleRed: {
    fontFamily: theme.fonts.headingBold,
    fontSize: 28,
    color: theme.colors.primary,
    lineHeight: 32,
    marginBottom: 8,
  },
  description: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 14,
    color: theme.colors.textSecondary,
    lineHeight: 20,
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardLabel: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 12,
    color: '#666',
    letterSpacing: 1,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  badgeText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 10,
    color: '#1E7E34',
  },
  kitName: {
    fontFamily: theme.fonts.headingBold,
    fontSize: 20,
    color: theme.colors.textPrimary,
    marginBottom: 16,
  },
  modalidadeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalidadeLabel: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 12,
    color: '#666',
  },
  modalidadeValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  modalidadeValue: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: theme.colors.textPrimary,
  },
  weightBox: {
    backgroundColor: '#F9F9F9',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    alignItems: 'center',
  },
  weightRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 4,
  },
  weightNumber: {
    fontFamily: theme.fonts.headingBold,
    fontSize: 32,
    color: theme.colors.textPrimary,
  },
  weightUnit: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 16,
    color: '#666',
    marginLeft: 4,
  },
  weightDescription: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 12,
    color: '#666',
    marginBottom: 12,
  },
  discountInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFEBEE',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  discountInfoText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 10,
    color: theme.colors.primary,
  },
  summaryLabel: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 12,
    color: '#666',
    letterSpacing: 1,
    marginBottom: 12,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  itemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  itemName: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 14,
    color: theme.colors.textPrimary,
  },
  itemWeight: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: theme.colors.textPrimary,
  },
  btnTrocarKit: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 20,
    paddingVertical: 12,
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
  },
  btnTrocarKitText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: theme.colors.textPrimary,
  },
  preferenceBox: {
    marginBottom: 24,
  },
  preferenceLabel: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 12,
    color: '#666',
    letterSpacing: 1,
    marginBottom: 12,
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  radioText: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 14,
    color: theme.colors.textPrimary,
  },
  warningBox: {
    flexDirection: 'row',
    backgroundColor: '#FFF5F5',
    padding: 16,
    borderRadius: 12,
    marginBottom: 32,
    alignItems: 'flex-start',
  },
  warningIcon: {
    marginTop: 2,
    marginRight: 12,
  },
  warningText: {
    flex: 1,
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 13,
    color: theme.colors.primary,
    lineHeight: 18,
  },
  footer: {
    gap: 12,
  },
  btnTreinarSemEquipamento: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnTreinarSemEquipamentoText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: '#999',
    textDecorationLine: 'underline',
  },
  btnConfirmar: {
    backgroundColor: theme.colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    borderRadius: 12,
    gap: 12,
  },
  btnConfirmarText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: '#FFF',
  },
  emptyCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 32,
    marginBottom: 24,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  emptyIconBox: {
    width: 80,
    height: 80,
    borderRadius: 16,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  emptyTitle: {
    fontFamily: theme.fonts.headingBold,
    fontSize: 18,
    color: theme.colors.textPrimary,
    marginBottom: 12,
    textAlign: 'center',
  },
  emptyDescription: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 14,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 32,
  },
  btnCriarKit: {
    backgroundColor: theme.colors.primary,
    width: '100%',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  btnCriarKitText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: '#FFF',
    letterSpacing: 1,
  },
  emptyFooterWrapper: {
    gap: 16,
    marginTop: 16,
  },
  btnTreinarSemEquipamentoOutline: {
    borderWidth: 1,
    borderColor: '#EAEAEA',
    backgroundColor: '#FAFAFA',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnTreinarSemEquipamentoOutlineText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: theme.colors.primary,
    letterSpacing: 1,
  },
  emptyFooterDescription: {
    fontFamily: theme.fonts.bodyRegular,
    fontSize: 12,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: 8,
  },
  btnConfirmarDisabled: {
    backgroundColor: '#EBEBEB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    borderRadius: 8,
    gap: 12,
  },
  btnConfirmarDisabledText: {
    fontFamily: theme.fonts.bodyBold,
    fontSize: 14,
    color: '#999',
    letterSpacing: 1,
  },
});
