version: '3.9'

services:
  hydrasense-mysql:
    image: mysql:8
    container_name: hydrasense-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: hydrasense
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./Back-End
    container_name: hydrasense-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      hydrasense-mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./Front-End/sc-hydrasense-web
    container_name: hydrasense-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: